# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  # Go formatting and linting
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w, -s]
        files: \.go$

      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go
        language: system
        args: [test, -v, ./...]
        files: \.go$
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        args: [mod, tidy]
        files: go\.mod$
        pass_filenames: false

  # Generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
